### PR TITLE
Update sphinx theme

### PR DESCRIPTION
**Pull request by arnaucasau**
### Summary
Updates to new Ecosystem theme.

For more information: https://github.com/Qiskit/qiskit_sphinx_theme/issues/232

### CODE REVIEW

**Comment by fretchen** [comment]
Is it possible that this update also requires us to update the requirements for python to be >=3.8 ?

**Comment by arnaucasau** [comment]
@fretchen Yes, in order to use the new Sphinx theme (version 1.16) it requires at least python 3.8

**Comment by fretchen** [comment]
In this case I do not see any reason to keep python-3.7 [here](https://github.com/qiskit-community/qiskit-cold-atom/blob/main/.github/workflows/main.yml). Could you update this ? 

Optional question: Is there any upper limit on python versions against which we can test within `qiskit-community`? In other words. Could we update the tests to work for python 3.8 to 3.11 or something like this ?

**Comment by Eric-Arellano** [comment]
> Yes, in order to use the new Sphinx theme (version 1.16) it requires at least python 3.8

To clarify, Sphinx is a dev requirement. It has no impact on end users. But indeed, modern Sphinx requires 3.8+. Either way, Python 3.7 is now EOL (end of life), so it's a good idea to drop it.

> Could you update this ?

@arnaucasau I recommend you have a dedicated PR that drops Python 3.7 as a precursor to this PR. You'll want to update all the GitHub actions files, along with the project metadata:

https://github.com/qiskit-community/qiskit-cold-atom/blob/36e62d7e112589fcb379998a1932860371b6c900/setup.py#L46-L47

https://github.com/qiskit-community/qiskit-cold-atom/blob/36e62d7e112589fcb379998a1932860371b6c900/setup.py#L56

> In other words. Could we update the tests to work for python 3.8 to 3.11 or something like this ?

Qiskit should work well with 3.11, the latest stable release. I would recommend testing 3.8 and 3.11 in CI, and not 3.9 anymore. Given Python's backward compatibility, 3.9 and 3.10 should work if 3.8 and 3.11 also work. @arnaucasau this would be good to include in your PR to drop Python 3.7.

**Review by fretchen — CHANGES_REQUESTED** [review]
Almost good to me if you could add the reno file.

**Comment by Eric-Arellano** [comment]
> Almost good to me if you could add the reno file.

Saying what? This PR now only changes the docs theme, which has little user impact. Arnau changed the Python version separately in https://github.com/qiskit-community/qiskit-cold-atom/pull/82.

**Comment by fretchen** [comment]
Ok. I see your point.

Eric Arellano ***@***.***> schrieb am Do. 19. Okt. 2023 um
21:52:

**Review by fretchen — APPROVED** [review]
LGTM.

**Comment by Eric-Arellano** [comment]
Thanks, @fretchen! Arnau doesn't have write access so will need a maintainer to merge this.

**Pull request merged**
